/*  File auto-generated by Q-ASN1. */
#include "ASN1_includes.h"

ASN1_Object* Make_UInt8(const char* name, const char* tag, bool optional, bool explTag, ASN1_Integer* defaultVal) {
  ASN1_Object* var_1 = new ASN1_Integer(name, tag, optional, explTag, defaultVal);
  return var_1;
}

ASN1_Object* Make_UInt15(const char* name, const char* tag, bool optional, bool explTag, ASN1_Integer* defaultVal) {
  ASN1_Object* var_2 = new ASN1_Integer(name, tag, optional, explTag, defaultVal);
  return var_2;
}

ASN1_Object* Make_UInt16(const char* name, const char* tag, bool optional, bool explTag, ASN1_Integer* defaultVal) {
  ASN1_Object* var_3 = new ASN1_Integer(name, tag, optional, explTag, defaultVal);
  return var_3;
}

ASN1_Object* Make_UInt31(const char* name, const char* tag, bool optional, bool explTag, ASN1_Integer* defaultVal) {
  ASN1_Object* var_4 = new ASN1_Integer(name, tag, optional, explTag, defaultVal);
  return var_4;
}

ASN1_Object* Make_ApplicationIdentifier(const char* name, const char* tag, bool optional, bool explTag, ASN1_OctetString* defaultVal) {
  ASN1_Object* var_5 = new ASN1_OctetString(name, tag, optional, explTag, defaultVal);
  return var_5;
}

void Make_PEHeader(ASN1_Object** arr) {
  ASN1_Object* mandated_6 = new ASN1_Null("mandated", "80", true, false, nullptr);
  ASN1_Object* identification_7 = Make_UInt15("identification", "81", false, false, nullptr);
  arr[0] = mandated_6; arr[1] = identification_7;
}

void Make_PE_Dummy(ASN1_Object**) {

}

void Make_ServicesList(ASN1_Object** arr) {
  ASN1_Object* contactless_8 = new ASN1_Null("contactless", "80", true, false, nullptr);
  ASN1_Object* usim_9 = new ASN1_Null("usim", "81", true, false, nullptr);
  ASN1_Object* isim_10 = new ASN1_Null("isim", "82", true, false, nullptr);
  ASN1_Object* csim_11 = new ASN1_Null("csim", "83", true, false, nullptr);
  ASN1_Object* milenage_12 = new ASN1_Null("milenage", "84", true, false, nullptr);
  ASN1_Object* tuak_13 = new ASN1_Null("tuak", "85", true, false, nullptr);
  ASN1_Object* cave_14 = new ASN1_Null("cave", "86", true, false, nullptr);
  ASN1_Object* gba_usim_15 = new ASN1_Null("gba_usim", "87", true, false, nullptr);
  ASN1_Object* gba_isim_16 = new ASN1_Null("gba_isim", "88", true, false, nullptr);
  ASN1_Object* mbms_17 = new ASN1_Null("mbms", "89", true, false, nullptr);
  ASN1_Object* eap_18 = new ASN1_Null("eap", "8A", true, false, nullptr);
  ASN1_Object* javacard_19 = new ASN1_Null("javacard", "8B", true, false, nullptr);
  ASN1_Object* multos_20 = new ASN1_Null("multos", "8C", true, false, nullptr);
  arr[0] = contactless_8; arr[1] = usim_9; arr[2] = isim_10; arr[3] = csim_11; arr[4] = milenage_12; arr[5] = tuak_13; arr[6] = cave_14; arr[7] = gba_usim_15; arr[8] = gba_isim_16; arr[9] = mbms_17;
  arr[10] = eap_18; arr[11] = javacard_19; arr[12] = multos_20;
}

ASN1_Object* SequenceOf1_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_21 = new ASN1_ObjectID("SeqOfVar", "80", false, false, nullptr);
  return SeqOfVar_21;
}

void Make_ProfileHeader(ASN1_Object** arr) {
  ASN1_Object* major_version_22 = Make_UInt8("major_version", "80", false, false, nullptr);
  ASN1_Object* minor_version_23 = Make_UInt8("minor_version", "81", false, false, nullptr);
  ASN1_Object* profileType_24 = new ASN1_UTF8String("profileType", "82", true, false, nullptr);
  ASN1_Object* iccid_25 = new ASN1_OctetString("iccid", "83", false, false, nullptr);
  ASN1_Object* pol_26 = new ASN1_OctetString("pol", "84", true, false, nullptr);
  ASN1_Object* arr_eUICC_Mandatory_services_27[13];
  Make_ServicesList(arr_eUICC_Mandatory_services_27);
  ASN1_Object* eUICC_Mandatory_services_27 = new ASN1_Sequence(arr_eUICC_Mandatory_services_27, 13, "eUICC_Mandatory_services", "A5", false, false, nullptr, true);
  ASN1_Object* eUICC_Mandatory_GFSTEList_28 = new ASN1_SequenceOf({&SequenceOf1_SeqOfCallback, nullptr}, "eUICC_Mandatory_GFSTEList", "A6", false, false, nullptr);
  arr[0] = major_version_22; arr[1] = minor_version_23; arr[2] = profileType_24; arr[3] = iccid_25; arr[4] = pol_26; arr[5] = eUICC_Mandatory_services_27; arr[6] = eUICC_Mandatory_GFSTEList_28;
}

void Make_ProprietaryInfo(ASN1_Object** arr) {
  ASN1_Object* specialFileInformation_29 = new ASN1_OctetString("specialFileInformation", "C0", false, false, nullptr);
  ASN1_Object* fillPattern_30 = new ASN1_OctetString("fillPattern", "C1", true, false, nullptr);
  ASN1_Object* repeatPattern_31 = new ASN1_OctetString("repeatPattern", "C2", true, false, nullptr);
  arr[0] = specialFileInformation_29; arr[1] = fillPattern_30; arr[2] = repeatPattern_31;
}

void Make_Fcp(ASN1_Object** arr) {
  ASN1_Object* fileDescriptor_32 = new ASN1_OctetString("fileDescriptor", "82", true, false, nullptr);
  ASN1_Object* fileID_33 = new ASN1_OctetString("fileID", "83", true, false, nullptr);
  ASN1_Object* dfName_34 = Make_ApplicationIdentifier("dfName", "84", true, false, nullptr);
  ASN1_Object* lcsi_35 = new ASN1_OctetString("lcsi", "8A", false, false, nullptr);
  ASN1_Object* securityAttributesReferenced_36 = new ASN1_OctetString("securityAttributesReferenced", "8B", true, false, nullptr);
  ASN1_Object* efFileSize_37 = new ASN1_OctetString("efFileSize", "80", true, false, nullptr);
  ASN1_Object* pinStatusTemplateDO_38 = new ASN1_OctetString("pinStatusTemplateDO", "C6", true, false, nullptr);
  ASN1_Object* shortEFID_39 = new ASN1_OctetString("shortEFID", "88", true, false, nullptr);
  ASN1_Object* arr_proprietaryEFInfo_40[3];
  Make_ProprietaryInfo(arr_proprietaryEFInfo_40);
  ASN1_Object* proprietaryEFInfo_40 = new ASN1_Sequence(arr_proprietaryEFInfo_40, 3, "proprietaryEFInfo", "A5", true, false, nullptr, true);
  ASN1_Object* linkPath_41 = new ASN1_OctetString("linkPath", "C7", true, false, nullptr);
  arr[0] = fileDescriptor_32; arr[1] = fileID_33; arr[2] = dfName_34; arr[3] = lcsi_35; arr[4] = securityAttributesReferenced_36; arr[5] = efFileSize_37; arr[6] = pinStatusTemplateDO_38;
  arr[7] = shortEFID_39; arr[8] = proprietaryEFInfo_40; arr[9] = linkPath_41;
}

ASN1_Object* Choice2_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* doNotCreate_42 = new ASN1_Null("doNotCreate", "80", false, false, nullptr);
    return doNotCreate_42;
  }
  if (index == 1) {
    ASN1_Object* arr_fileDescriptor_43[10];
    Make_Fcp(arr_fileDescriptor_43);
    ASN1_Object* fileDescriptor_43 = new ASN1_Sequence(arr_fileDescriptor_43, 10, "fileDescriptor", "A1", false, false, nullptr, true);
    return fileDescriptor_43;
  }
  if (index == 2) {
    ASN1_Object* fillFileOffset_44 = Make_UInt16("fillFileOffset", "82", false, false, nullptr);
    return fillFileOffset_44;
  }
  if (index == 3) {
    ASN1_Object* fillFileContent_45 = new ASN1_OctetString("fillFileContent", "83", false, false, nullptr);
    return fillFileContent_45;
  }
  return nullptr;
}

ASN1_Object* File_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_46 = new ASN1_Choice({&Choice2_ChoiceCallback, nullptr}, 4, "SeqOfVar", "A0", false, true, nullptr);
  return SeqOfVar_46;
}

void Make_PE_MF(ASN1_Object** arr) {
  ASN1_Object* arr_mf_header_47[2];
  Make_PEHeader(arr_mf_header_47);
  ASN1_Object* mf_header_47 = new ASN1_Sequence(arr_mf_header_47, 2, "mf_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_48 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* mf_49 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "mf", "A2", false, false, nullptr);
  ASN1_Object* ef_pl_50 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pl", "A3", true, false, nullptr);
  ASN1_Object* ef_iccid_51 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_iccid", "A4", false, false, nullptr);
  ASN1_Object* ef_dir_52 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_dir", "A5", false, false, nullptr);
  ASN1_Object* ef_arr_53 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_arr", "A6", false, false, nullptr);
  arr[0] = mf_header_47; arr[1] = templateID_48; arr[2] = mf_49; arr[3] = ef_pl_50; arr[4] = ef_iccid_51; arr[5] = ef_dir_52; arr[6] = ef_arr_53;
}

void Make_PE_CD(ASN1_Object** arr) {
  ASN1_Object* arr_cd_header_54[2];
  Make_PEHeader(arr_cd_header_54);
  ASN1_Object* cd_header_54 = new ASN1_Sequence(arr_cd_header_54, 2, "cd_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_55 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* df_cd_56 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_cd", "A2", false, false, nullptr);
  ASN1_Object* ef_launchpad_57 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_launchpad", "A3", true, false, nullptr);
  ASN1_Object* ef_icon_58 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_icon", "A4", true, false, nullptr);
  arr[0] = cd_header_54; arr[1] = templateID_55; arr[2] = df_cd_56; arr[3] = ef_launchpad_57; arr[4] = ef_icon_58;
}

void Make_PE_TELECOM(ASN1_Object** arr) {
  ASN1_Object* arr_telecom_header_59[2];
  Make_PEHeader(arr_telecom_header_59);
  ASN1_Object* telecom_header_59 = new ASN1_Sequence(arr_telecom_header_59, 2, "telecom_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_60 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* df_telecom_61 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_telecom", "A2", false, false, nullptr);
  ASN1_Object* ef_arr_62 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_arr", "A3", true, false, nullptr);
  ASN1_Object* ef_rma_63 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_rma", "A4", true, false, nullptr);
  ASN1_Object* ef_sume_64 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sume", "A5", true, false, nullptr);
  ASN1_Object* ef_ice_dn_65 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ice_dn", "A6", true, false, nullptr);
  ASN1_Object* ef_ice_ff_66 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ice_ff", "A7", true, false, nullptr);
  ASN1_Object* ef_psismsc_67 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_psismsc", "A8", true, false, nullptr);
  ASN1_Object* df_graphics_68 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_graphics", "A9", true, false, nullptr);
  ASN1_Object* ef_img_69 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_img", "AA", true, false, nullptr);
  ASN1_Object* ef_iidf_70 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_iidf", "AB", true, false, nullptr);
  ASN1_Object* ef_ice_graphics_71 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ice_graphics", "AC", true, false, nullptr);
  ASN1_Object* ef_launch_scws_72 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_launch_scws", "AD", true, false, nullptr);
  ASN1_Object* ef_icon_73 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_icon", "AE", true, false, nullptr);
  ASN1_Object* df_phonebook_74 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_phonebook", "AF", true, false, nullptr);
  ASN1_Object* ef_pbr_75 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pbr", "B0", true, false, nullptr);
  ASN1_Object* ef_ext1_76 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext1", "B1", true, false, nullptr);
  ASN1_Object* ef_aas_77 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_aas", "B2", true, false, nullptr);
  ASN1_Object* ef_gas_78 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gas", "B3", true, false, nullptr);
  ASN1_Object* ef_psc_79 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_psc", "B4", true, false, nullptr);
  ASN1_Object* ef_cc_80 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cc", "B5", true, false, nullptr);
  ASN1_Object* ef_puid_81 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_puid", "B6", true, false, nullptr);
  ASN1_Object* ef_iap_82 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_iap", "B7", true, false, nullptr);
  ASN1_Object* ef_adn_83 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_adn", "B8", true, false, nullptr);
  ASN1_Object* ef_pbc_84 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pbc", "B9", true, false, nullptr);
  ASN1_Object* ef_anr_85 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_anr", "BA", true, false, nullptr);
  ASN1_Object* ef_puri_86 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_puri", "BB", true, false, nullptr);
  ASN1_Object* ef_email_87 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_email", "BC", true, false, nullptr);
  ASN1_Object* ef_sne_88 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sne", "BD", true, false, nullptr);
  ASN1_Object* ef_uid_89 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_uid", "BE", true, false, nullptr);
  ASN1_Object* ef_grp_90 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_grp", "BF1F", true, false, nullptr);
  ASN1_Object* ef_ccp1_91 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ccp1", "BF20", true, false, nullptr);
  ASN1_Object* df_multimedia_92 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_multimedia", "BF21", true, false, nullptr);
  ASN1_Object* ef_mml_93 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mml", "BF22", true, false, nullptr);
  ASN1_Object* ef_mmdf_94 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmdf", "BF23", true, false, nullptr);
  ASN1_Object* df_mmss_95 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_mmss", "BF24", true, false, nullptr);
  ASN1_Object* ef_mlpl_96 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mlpl", "BF25", true, false, nullptr);
  ASN1_Object* ef_mspl_97 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mspl", "BF26", true, false, nullptr);
  ASN1_Object* ef_mmssmode_98 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmssmode", "BF27", true, false, nullptr);
  arr[0] = telecom_header_59; arr[1] = templateID_60; arr[2] = df_telecom_61; arr[3] = ef_arr_62; arr[4] = ef_rma_63; arr[5] = ef_sume_64; arr[6] = ef_ice_dn_65; arr[7] = ef_ice_ff_66;
  arr[8] = ef_psismsc_67; arr[9] = df_graphics_68; arr[10] = ef_img_69; arr[11] = ef_iidf_70; arr[12] = ef_ice_graphics_71; arr[13] = ef_launch_scws_72; arr[14] = ef_icon_73; arr[15] = df_phonebook_74;
  arr[16] = ef_pbr_75; arr[17] = ef_ext1_76; arr[18] = ef_aas_77; arr[19] = ef_gas_78; arr[20] = ef_psc_79; arr[21] = ef_cc_80; arr[22] = ef_puid_81; arr[23] = ef_iap_82; arr[24] = ef_adn_83;
  arr[25] = ef_pbc_84; arr[26] = ef_anr_85; arr[27] = ef_puri_86; arr[28] = ef_email_87; arr[29] = ef_sne_88; arr[30] = ef_uid_89; arr[31] = ef_grp_90; arr[32] = ef_ccp1_91; arr[33] = df_multimedia_92;
  arr[34] = ef_mml_93; arr[35] = ef_mmdf_94; arr[36] = df_mmss_95; arr[37] = ef_mlpl_96; arr[38] = ef_mspl_97; arr[39] = ef_mmssmode_98;
}

void Make_PE_USIM(ASN1_Object** arr) {
  ASN1_Object* arr_usim_header_99[2];
  Make_PEHeader(arr_usim_header_99);
  ASN1_Object* usim_header_99 = new ASN1_Sequence(arr_usim_header_99, 2, "usim_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_100 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* adf_usim_101 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "adf_usim", "A2", false, false, nullptr);
  ASN1_Object* ef_imsi_102 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_imsi", "A3", false, false, nullptr);
  ASN1_Object* ef_arr_103 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_arr", "A4", false, false, nullptr);
  ASN1_Object* ef_keys_104 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_keys", "A5", true, false, nullptr);
  ASN1_Object* ef_keysPS_105 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_keysPS", "A6", true, false, nullptr);
  ASN1_Object* ef_hpplmn_106 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_hpplmn", "A7", true, false, nullptr);
  ASN1_Object* ef_ust_107 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ust", "A8", false, false, nullptr);
  ASN1_Object* ef_fdn_108 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_fdn", "A9", true, false, nullptr);
  ASN1_Object* ef_sms_109 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sms", "AA", true, false, nullptr);
  ASN1_Object* ef_smsp_110 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smsp", "AB", true, false, nullptr);
  ASN1_Object* ef_smss_111 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smss", "AC", true, false, nullptr);
  ASN1_Object* ef_spn_112 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_spn", "AD", false, false, nullptr);
  ASN1_Object* ef_est_113 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_est", "AE", false, false, nullptr);
  ASN1_Object* ef_start_hfn_114 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_start_hfn", "AF", true, false, nullptr);
  ASN1_Object* ef_threshold_115 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_threshold", "B0", true, false, nullptr);
  ASN1_Object* ef_psloci_116 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_psloci", "B1", true, false, nullptr);
  ASN1_Object* ef_acc_117 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_acc", "B2", false, false, nullptr);
  ASN1_Object* ef_fplmn_118 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_fplmn", "B3", true, false, nullptr);
  ASN1_Object* ef_loci_119 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_loci", "B4", true, false, nullptr);
  ASN1_Object* ef_ad_120 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ad", "B5", true, false, nullptr);
  ASN1_Object* ef_ecc_121 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ecc", "B6", false, false, nullptr);
  ASN1_Object* ef_netpar_122 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_netpar", "B7", true, false, nullptr);
  ASN1_Object* ef_epsloci_123 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_epsloci", "B8", true, false, nullptr);
  ASN1_Object* ef_epsnsc_124 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_epsnsc", "B9", true, false, nullptr);
  arr[0] = usim_header_99; arr[1] = templateID_100; arr[2] = adf_usim_101; arr[3] = ef_imsi_102; arr[4] = ef_arr_103; arr[5] = ef_keys_104; arr[6] = ef_keysPS_105; arr[7] = ef_hpplmn_106;
  arr[8] = ef_ust_107; arr[9] = ef_fdn_108; arr[10] = ef_sms_109; arr[11] = ef_smsp_110; arr[12] = ef_smss_111; arr[13] = ef_spn_112; arr[14] = ef_est_113; arr[15] = ef_start_hfn_114;
  arr[16] = ef_threshold_115; arr[17] = ef_psloci_116; arr[18] = ef_acc_117; arr[19] = ef_fplmn_118; arr[20] = ef_loci_119; arr[21] = ef_ad_120; arr[22] = ef_ecc_121; arr[23] = ef_netpar_122;
  arr[24] = ef_epsloci_123; arr[25] = ef_epsnsc_124;
}

void Make_PE_OPT_USIM(ASN1_Object** arr) {
  ASN1_Object* arr_optusim_header_125[2];
  Make_PEHeader(arr_optusim_header_125);
  ASN1_Object* optusim_header_125 = new ASN1_Sequence(arr_optusim_header_125, 2, "optusim_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_126 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* ef_li_127 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_li", "A2", true, false, nullptr);
  ASN1_Object* ef_acmax_128 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_acmax", "A3", true, false, nullptr);
  ASN1_Object* ef_acm_129 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_acm", "A4", true, false, nullptr);
  ASN1_Object* ef_gid1_130 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gid1", "A5", true, false, nullptr);
  ASN1_Object* ef_gid2_131 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gid2", "A6", true, false, nullptr);
  ASN1_Object* ef_msisdn_132 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_msisdn", "A7", true, false, nullptr);
  ASN1_Object* ef_puct_133 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_puct", "A8", true, false, nullptr);
  ASN1_Object* ef_cbmi_134 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cbmi", "A9", true, false, nullptr);
  ASN1_Object* ef_cbmid_135 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cbmid", "AA", true, false, nullptr);
  ASN1_Object* ef_sdn_136 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sdn", "AB", true, false, nullptr);
  ASN1_Object* ef_ext2_137 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext2", "AC", true, false, nullptr);
  ASN1_Object* ef_ext3_138 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext3", "AD", true, false, nullptr);
  ASN1_Object* ef_cbmir_139 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cbmir", "AE", true, false, nullptr);
  ASN1_Object* ef_plmnwact_140 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_plmnwact", "AF", true, false, nullptr);
  ASN1_Object* ef_oplmnwact_141 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_oplmnwact", "B0", true, false, nullptr);
  ASN1_Object* ef_hplmnwact_142 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_hplmnwact", "B1", true, false, nullptr);
  ASN1_Object* ef_dck_143 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_dck", "B2", true, false, nullptr);
  ASN1_Object* ef_cnl_144 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cnl", "B3", true, false, nullptr);
  ASN1_Object* ef_smsr_145 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smsr", "B4", true, false, nullptr);
  ASN1_Object* ef_bdn_146 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bdn", "B5", true, false, nullptr);
  ASN1_Object* ef_ext5_147 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext5", "B6", true, false, nullptr);
  ASN1_Object* ef_ccp2_148 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ccp2", "B7", true, false, nullptr);
  ASN1_Object* ef_ext4_149 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext4", "B8", true, false, nullptr);
  ASN1_Object* ef_acl_150 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_acl", "B9", true, false, nullptr);
  ASN1_Object* ef_cmi_151 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cmi", "BA", true, false, nullptr);
  ASN1_Object* ef_ici_152 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ici", "BB", true, false, nullptr);
  ASN1_Object* ef_oci_153 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_oci", "BC", true, false, nullptr);
  ASN1_Object* ef_ict_154 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ict", "BD", true, false, nullptr);
  ASN1_Object* ef_oct_155 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_oct", "BE", true, false, nullptr);
  ASN1_Object* ef_vgcs_156 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_vgcs", "BF1F", true, false, nullptr);
  ASN1_Object* ef_vgcss_157 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_vgcss", "BF20", true, false, nullptr);
  ASN1_Object* ef_vbs_158 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_vbs", "BF21", true, false, nullptr);
  ASN1_Object* ef_vbss_159 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_vbss", "BF22", true, false, nullptr);
  ASN1_Object* ef_emlpp_160 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_emlpp", "BF23", true, false, nullptr);
  ASN1_Object* ef_aeem_161 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_aeem", "BF24", true, false, nullptr);
  ASN1_Object* ef_hiddenkey_162 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_hiddenkey", "BF25", true, false, nullptr);
  ASN1_Object* ef_pnn_163 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pnn", "BF26", true, false, nullptr);
  ASN1_Object* ef_opl_164 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_opl", "BF27", true, false, nullptr);
  ASN1_Object* ef_mbdn_165 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mbdn", "BF28", true, false, nullptr);
  ASN1_Object* ef_ext6_166 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext6", "BF29", true, false, nullptr);
  ASN1_Object* ef_mbi_167 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mbi", "BF2A", true, false, nullptr);
  ASN1_Object* ef_mwis_168 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mwis", "BF2B", true, false, nullptr);
  ASN1_Object* ef_cfis_169 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cfis", "BF2C", true, false, nullptr);
  ASN1_Object* ef_ext7_170 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext7", "BF2D", true, false, nullptr);
  ASN1_Object* ef_spdi_171 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_spdi", "BF2E", true, false, nullptr);
  ASN1_Object* ef_mmsn_172 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsn", "BF2F", true, false, nullptr);
  ASN1_Object* ef_ext8_173 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext8", "BF30", true, false, nullptr);
  ASN1_Object* ef_mmsicp_174 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsicp", "BF31", true, false, nullptr);
  ASN1_Object* ef_mmsup_175 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsup", "BF32", true, false, nullptr);
  ASN1_Object* ef_mmsucp_176 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsucp", "BF33", true, false, nullptr);
  ASN1_Object* ef_nia_177 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_nia", "BF34", true, false, nullptr);
  ASN1_Object* ef_vgcsca_178 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_vgcsca", "BF35", true, false, nullptr);
  ASN1_Object* ef_gbabp_179 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gbabp", "BF36", true, false, nullptr);
  ASN1_Object* ef_msk_180 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_msk", "BF37", true, false, nullptr);
  ASN1_Object* ef_muk_181 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_muk", "BF38", true, false, nullptr);
  ASN1_Object* ef_ehplmn_182 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ehplmn", "BF39", true, false, nullptr);
  ASN1_Object* ef_gbanl_183 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gbanl", "BF3A", true, false, nullptr);
  ASN1_Object* ef_ehplmnpi_184 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ehplmnpi", "BF3B", true, false, nullptr);
  ASN1_Object* ef_lrplmnsi_185 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_lrplmnsi", "BF3C", true, false, nullptr);
  ASN1_Object* ef_nafkca_186 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_nafkca", "BF3D", true, false, nullptr);
  ASN1_Object* ef_spni_187 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_spni", "BF3E", true, false, nullptr);
  ASN1_Object* ef_ppni_188 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ppni", "BF3F", true, false, nullptr);
  ASN1_Object* ef_ncp_ip_189 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ncp_ip", "BF40", true, false, nullptr);
  ASN1_Object* ef_ufc_190 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ufc", "BF41", true, false, nullptr);
  ASN1_Object* ef_nasconfig_191 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_nasconfig", "BF42", true, false, nullptr);
  ASN1_Object* ef_uicciari_192 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_uicciari", "BF43", true, false, nullptr);
  ASN1_Object* ef_pws_193 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pws", "BF44", true, false, nullptr);
  ASN1_Object* ef_fdnuri_194 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_fdnuri", "BF45", true, false, nullptr);
  ASN1_Object* ef_bdnuri_195 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bdnuri", "BF46", true, false, nullptr);
  ASN1_Object* ef_sdnuri_196 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sdnuri", "BF47", true, false, nullptr);
  ASN1_Object* ef_iwl_197 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_iwl", "BF48", true, false, nullptr);
  ASN1_Object* ef_ips_198 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ips", "BF49", true, false, nullptr);
  ASN1_Object* ef_ipd_199 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ipd", "BF4A", true, false, nullptr);
  arr[0] = optusim_header_125; arr[1] = templateID_126; arr[2] = ef_li_127; arr[3] = ef_acmax_128; arr[4] = ef_acm_129; arr[5] = ef_gid1_130; arr[6] = ef_gid2_131; arr[7] = ef_msisdn_132;
  arr[8] = ef_puct_133; arr[9] = ef_cbmi_134; arr[10] = ef_cbmid_135; arr[11] = ef_sdn_136; arr[12] = ef_ext2_137; arr[13] = ef_ext3_138; arr[14] = ef_cbmir_139; arr[15] = ef_plmnwact_140;
  arr[16] = ef_oplmnwact_141; arr[17] = ef_hplmnwact_142; arr[18] = ef_dck_143; arr[19] = ef_cnl_144; arr[20] = ef_smsr_145; arr[21] = ef_bdn_146; arr[22] = ef_ext5_147; arr[23] = ef_ccp2_148;
  arr[24] = ef_ext4_149; arr[25] = ef_acl_150; arr[26] = ef_cmi_151; arr[27] = ef_ici_152; arr[28] = ef_oci_153; arr[29] = ef_ict_154; arr[30] = ef_oct_155; arr[31] = ef_vgcs_156;
  arr[32] = ef_vgcss_157; arr[33] = ef_vbs_158; arr[34] = ef_vbss_159; arr[35] = ef_emlpp_160; arr[36] = ef_aeem_161; arr[37] = ef_hiddenkey_162; arr[38] = ef_pnn_163; arr[39] = ef_opl_164;
  arr[40] = ef_mbdn_165; arr[41] = ef_ext6_166; arr[42] = ef_mbi_167; arr[43] = ef_mwis_168; arr[44] = ef_cfis_169; arr[45] = ef_ext7_170; arr[46] = ef_spdi_171; arr[47] = ef_mmsn_172;
  arr[48] = ef_ext8_173; arr[49] = ef_mmsicp_174; arr[50] = ef_mmsup_175; arr[51] = ef_mmsucp_176; arr[52] = ef_nia_177; arr[53] = ef_vgcsca_178; arr[54] = ef_gbabp_179; arr[55] = ef_msk_180;
  arr[56] = ef_muk_181; arr[57] = ef_ehplmn_182; arr[58] = ef_gbanl_183; arr[59] = ef_ehplmnpi_184; arr[60] = ef_lrplmnsi_185; arr[61] = ef_nafkca_186; arr[62] = ef_spni_187; arr[63] = ef_ppni_188;
  arr[64] = ef_ncp_ip_189; arr[65] = ef_ufc_190; arr[66] = ef_nasconfig_191; arr[67] = ef_uicciari_192; arr[68] = ef_pws_193; arr[69] = ef_fdnuri_194; arr[70] = ef_bdnuri_195; arr[71] = ef_sdnuri_196;
  arr[72] = ef_iwl_197; arr[73] = ef_ips_198; arr[74] = ef_ipd_199;
}

void Make_PE_PHONEBOOK(ASN1_Object** arr) {
  ASN1_Object* arr_phonebook_header_200[2];
  Make_PEHeader(arr_phonebook_header_200);
  ASN1_Object* phonebook_header_200 = new ASN1_Sequence(arr_phonebook_header_200, 2, "phonebook_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_201 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* df_phonebook_202 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_phonebook", "A2", false, false, nullptr);
  ASN1_Object* ef_pbr_203 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pbr", "A3", true, false, nullptr);
  ASN1_Object* ef_ext1_204 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext1", "A4", true, false, nullptr);
  ASN1_Object* ef_aas_205 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_aas", "A5", true, false, nullptr);
  ASN1_Object* ef_gas_206 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gas", "A6", true, false, nullptr);
  ASN1_Object* ef_psc_207 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_psc", "A7", true, false, nullptr);
  ASN1_Object* ef_cc_208 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cc", "A8", true, false, nullptr);
  ASN1_Object* ef_puid_209 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_puid", "A9", true, false, nullptr);
  ASN1_Object* ef_iap_210 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_iap", "AA", true, false, nullptr);
  ASN1_Object* ef_adn_211 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_adn", "AB", true, false, nullptr);
  ASN1_Object* ef_pbc_212 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pbc", "AC", true, false, nullptr);
  ASN1_Object* ef_anr_213 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_anr", "AD", true, false, nullptr);
  ASN1_Object* ef_puri_214 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_puri", "AE", true, false, nullptr);
  ASN1_Object* ef_email_215 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_email", "AF", true, false, nullptr);
  ASN1_Object* ef_sne_216 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sne", "B0", true, false, nullptr);
  ASN1_Object* ef_uid_217 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_uid", "B1", true, false, nullptr);
  ASN1_Object* ef_grp_218 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_grp", "B2", true, false, nullptr);
  ASN1_Object* ef_ccp1_219 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ccp1", "B3", true, false, nullptr);
  arr[0] = phonebook_header_200; arr[1] = templateID_201; arr[2] = df_phonebook_202; arr[3] = ef_pbr_203; arr[4] = ef_ext1_204; arr[5] = ef_aas_205; arr[6] = ef_gas_206; arr[7] = ef_psc_207;
  arr[8] = ef_cc_208; arr[9] = ef_puid_209; arr[10] = ef_iap_210; arr[11] = ef_adn_211; arr[12] = ef_pbc_212; arr[13] = ef_anr_213; arr[14] = ef_puri_214; arr[15] = ef_email_215; arr[16] = ef_sne_216;
  arr[17] = ef_uid_217; arr[18] = ef_grp_218; arr[19] = ef_ccp1_219;
}

void Make_PE_GSM_ACCESS(ASN1_Object** arr) {
  ASN1_Object* arr_gsm_access_header_220[2];
  Make_PEHeader(arr_gsm_access_header_220);
  ASN1_Object* gsm_access_header_220 = new ASN1_Sequence(arr_gsm_access_header_220, 2, "gsm_access_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_221 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* df_gsm_access_222 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "df_gsm_access", "A2", false, false, nullptr);
  ASN1_Object* ef_kc_223 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_kc", "A3", true, false, nullptr);
  ASN1_Object* ef_kcgprs_224 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_kcgprs", "A4", true, false, nullptr);
  ASN1_Object* ef_cpbcch_225 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cpbcch", "A5", true, false, nullptr);
  ASN1_Object* ef_invscan_226 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_invscan", "A6", true, false, nullptr);
  arr[0] = gsm_access_header_220; arr[1] = templateID_221; arr[2] = df_gsm_access_222; arr[3] = ef_kc_223; arr[4] = ef_kcgprs_224; arr[5] = ef_cpbcch_225; arr[6] = ef_invscan_226;
}

void Make_PE_ISIM(ASN1_Object** arr) {
  ASN1_Object* arr_isim_header_227[2];
  Make_PEHeader(arr_isim_header_227);
  ASN1_Object* isim_header_227 = new ASN1_Sequence(arr_isim_header_227, 2, "isim_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_228 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* adf_isim_229 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "adf_isim", "A2", false, false, nullptr);
  ASN1_Object* ef_impi_230 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_impi", "A3", false, false, nullptr);
  ASN1_Object* ef_impu_231 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_impu", "A4", false, false, nullptr);
  ASN1_Object* ef_domain_232 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_domain", "A5", false, false, nullptr);
  ASN1_Object* ef_ist_233 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ist", "A6", false, false, nullptr);
  ASN1_Object* ef_ad_234 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ad", "A7", true, false, nullptr);
  ASN1_Object* ef_arr_235 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_arr", "A8", false, false, nullptr);
  arr[0] = isim_header_227; arr[1] = templateID_228; arr[2] = adf_isim_229; arr[3] = ef_impi_230; arr[4] = ef_impu_231; arr[5] = ef_domain_232; arr[6] = ef_ist_233; arr[7] = ef_ad_234;
  arr[8] = ef_arr_235;
}

void Make_PE_OPT_ISIM(ASN1_Object** arr) {
  ASN1_Object* arr_optisim_header_236[2];
  Make_PEHeader(arr_optisim_header_236);
  ASN1_Object* optisim_header_236 = new ASN1_Sequence(arr_optisim_header_236, 2, "optisim_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_237 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* ef_pcscf_238 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_pcscf", "A2", true, false, nullptr);
  ASN1_Object* ef_sms_239 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sms", "A3", true, false, nullptr);
  ASN1_Object* ef_smsp_240 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smsp", "A4", true, false, nullptr);
  ASN1_Object* ef_smss_241 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smss", "A5", true, false, nullptr);
  ASN1_Object* ef_smsr_242 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smsr", "A6", true, false, nullptr);
  ASN1_Object* ef_gbabp_243 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gbabp", "A7", true, false, nullptr);
  ASN1_Object* ef_gbanl_244 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gbanl", "A8", true, false, nullptr);
  ASN1_Object* ef_nafkca_245 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_nafkca", "A9", true, false, nullptr);
  ASN1_Object* ef_uicciari_246 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_uicciari", "AA", true, false, nullptr);
  ASN1_Object* ef_psismsc_247 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_psismsc", "AB", true, false, nullptr);
  arr[0] = optisim_header_236; arr[1] = templateID_237; arr[2] = ef_pcscf_238; arr[3] = ef_sms_239; arr[4] = ef_smsp_240; arr[5] = ef_smss_241; arr[6] = ef_smsr_242; arr[7] = ef_gbabp_243;
  arr[8] = ef_gbanl_244; arr[9] = ef_nafkca_245; arr[10] = ef_uicciari_246; arr[11] = ef_psismsc_247;
}

void Make_PE_CSIM(ASN1_Object** arr) {
  ASN1_Object* arr_csim_header_248[2];
  Make_PEHeader(arr_csim_header_248);
  ASN1_Object* csim_header_248 = new ASN1_Sequence(arr_csim_header_248, 2, "csim_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_249 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* adf_csim_250 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "adf_csim", "A2", false, false, nullptr);
  ASN1_Object* ef_arr_251 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_arr", "A3", false, false, nullptr);
  ASN1_Object* ef_call_count_252 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_call_count", "A4", false, false, nullptr);
  ASN1_Object* ef_imsi_m_253 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_imsi_m", "A5", false, false, nullptr);
  ASN1_Object* ef_imsi_t_254 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_imsi_t", "A6", false, false, nullptr);
  ASN1_Object* ef_tmsi_255 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_tmsi", "A7", false, false, nullptr);
  ASN1_Object* ef_ah_256 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ah", "A8", false, false, nullptr);
  ASN1_Object* ef_aop_257 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_aop", "A9", false, false, nullptr);
  ASN1_Object* ef_aloc_258 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_aloc", "AA", false, false, nullptr);
  ASN1_Object* ef_cdmahome_259 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cdmahome", "AB", false, false, nullptr);
  ASN1_Object* ef_znregi_260 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_znregi", "AC", false, false, nullptr);
  ASN1_Object* ef_snregi_261 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_snregi", "AD", false, false, nullptr);
  ASN1_Object* ef_distregi_262 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_distregi", "AE", false, false, nullptr);
  ASN1_Object* ef_accolc_263 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_accolc", "AF", false, false, nullptr);
  ASN1_Object* ef_term_264 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_term", "B0", false, false, nullptr);
  ASN1_Object* ef_acp_265 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_acp", "B1", false, false, nullptr);
  ASN1_Object* ef_prl_266 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_prl", "B2", false, false, nullptr);
  ASN1_Object* ef_ruimid_267 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ruimid", "B3", false, false, nullptr);
  ASN1_Object* ef_csim_st_268 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_csim_st", "B4", false, false, nullptr);
  ASN1_Object* ef_spc_269 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_spc", "B5", false, false, nullptr);
  ASN1_Object* ef_otapaspc_270 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_otapaspc", "B6", false, false, nullptr);
  ASN1_Object* ef_namlock_271 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_namlock", "B7", false, false, nullptr);
  ASN1_Object* ef_ota_272 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ota", "B8", false, false, nullptr);
  ASN1_Object* ef_sp_273 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sp", "B9", false, false, nullptr);
  ASN1_Object* ef_esn_meid_me_274 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_esn_meid_me", "BA", false, false, nullptr);
  ASN1_Object* ef_li_275 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_li", "BB", false, false, nullptr);
  ASN1_Object* ef_usgind_276 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_usgind", "BC", false, false, nullptr);
  ASN1_Object* ef_ad_277 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ad", "BD", false, false, nullptr);
  ASN1_Object* ef_max_prl_278 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_max_prl", "BE", false, false, nullptr);
  ASN1_Object* ef_spcs_279 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_spcs", "BF1F", false, false, nullptr);
  ASN1_Object* ef_mecrp_280 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mecrp", "BF20", false, false, nullptr);
  ASN1_Object* ef_home_tag_281 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_home_tag", "BF21", false, false, nullptr);
  ASN1_Object* ef_group_tag_282 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_group_tag", "BF22", false, false, nullptr);
  ASN1_Object* ef_specific_tag_283 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_specific_tag", "BF23", false, false, nullptr);
  ASN1_Object* ef_call_prompt_284 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_call_prompt", "BF24", false, false, nullptr);
  arr[0] = csim_header_248; arr[1] = templateID_249; arr[2] = adf_csim_250; arr[3] = ef_arr_251; arr[4] = ef_call_count_252; arr[5] = ef_imsi_m_253; arr[6] = ef_imsi_t_254; arr[7] = ef_tmsi_255;
  arr[8] = ef_ah_256; arr[9] = ef_aop_257; arr[10] = ef_aloc_258; arr[11] = ef_cdmahome_259; arr[12] = ef_znregi_260; arr[13] = ef_snregi_261; arr[14] = ef_distregi_262; arr[15] = ef_accolc_263;
  arr[16] = ef_term_264; arr[17] = ef_acp_265; arr[18] = ef_prl_266; arr[19] = ef_ruimid_267; arr[20] = ef_csim_st_268; arr[21] = ef_spc_269; arr[22] = ef_otapaspc_270; arr[23] = ef_namlock_271;
  arr[24] = ef_ota_272; arr[25] = ef_sp_273; arr[26] = ef_esn_meid_me_274; arr[27] = ef_li_275; arr[28] = ef_usgind_276; arr[29] = ef_ad_277; arr[30] = ef_max_prl_278; arr[31] = ef_spcs_279;
  arr[32] = ef_mecrp_280; arr[33] = ef_home_tag_281; arr[34] = ef_group_tag_282; arr[35] = ef_specific_tag_283; arr[36] = ef_call_prompt_284;
}

void Make_PE_OPT_CSIM(ASN1_Object** arr) {
  ASN1_Object* arr_optcsim_header_285[2];
  Make_PEHeader(arr_optcsim_header_285);
  ASN1_Object* optcsim_header_285 = new ASN1_Sequence(arr_optcsim_header_285, 2, "optcsim_header", "A0", false, false, nullptr, true);
  ASN1_Object* templateID_286 = new ASN1_ObjectID("templateID", "81", false, false, nullptr);
  ASN1_Object* ef_ssci_287 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ssci", "A2", true, false, nullptr);
  ASN1_Object* ef_fdn_288 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_fdn", "A3", true, false, nullptr);
  ASN1_Object* ef_sms_289 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sms", "A4", true, false, nullptr);
  ASN1_Object* ef_smsp_290 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smsp", "A5", true, false, nullptr);
  ASN1_Object* ef_smss_291 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smss", "A6", true, false, nullptr);
  ASN1_Object* ef_ssfc_292 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ssfc", "A7", true, false, nullptr);
  ASN1_Object* ef_spn_293 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_spn", "A8", true, false, nullptr);
  ASN1_Object* ef_mdn_294 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mdn", "A9", true, false, nullptr);
  ASN1_Object* ef_ecc_295 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ecc", "AA", true, false, nullptr);
  ASN1_Object* ef_me3gpdopc_296 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_me3gpdopc", "AB", true, false, nullptr);
  ASN1_Object* ef_3gpdopm_297 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_3gpdopm", "AC", true, false, nullptr);
  ASN1_Object* ef_sipcap_298 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sipcap", "AD", true, false, nullptr);
  ASN1_Object* ef_mipcap_299 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mipcap", "AE", true, false, nullptr);
  ASN1_Object* ef_sipupp_300 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sipupp", "AF", true, false, nullptr);
  ASN1_Object* ef_mipupp_301 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mipupp", "B0", true, false, nullptr);
  ASN1_Object* ef_sipsp_302 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sipsp", "B1", true, false, nullptr);
  ASN1_Object* ef_mipsp_303 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mipsp", "B2", true, false, nullptr);
  ASN1_Object* ef_sippapss_304 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sippapss", "B3", true, false, nullptr);
  ASN1_Object* ef_puzl_305 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_puzl", "B4", true, false, nullptr);
  ASN1_Object* ef_maxpuzl_306 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_maxpuzl", "B5", true, false, nullptr);
  ASN1_Object* ef_hrpdcap_307 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_hrpdcap", "B6", true, false, nullptr);
  ASN1_Object* ef_hrpdupp_308 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_hrpdupp", "B7", true, false, nullptr);
  ASN1_Object* ef_csspr_309 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_csspr", "B8", true, false, nullptr);
  ASN1_Object* ef_atc_310 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_atc", "B9", true, false, nullptr);
  ASN1_Object* ef_eprl_311 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_eprl", "BA", true, false, nullptr);
  ASN1_Object* ef_bcsmscfg_312 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bcsmscfg", "BB", true, false, nullptr);
  ASN1_Object* ef_bcsmspref_313 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bcsmspref", "BC", true, false, nullptr);
  ASN1_Object* ef_bcsmstable_314 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bcsmstable", "BD", true, false, nullptr);
  ASN1_Object* ef_bcsmsp_315 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bcsmsp", "BE", true, false, nullptr);
  ASN1_Object* ef_bakpara_316 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_bakpara", "BF1F", true, false, nullptr);
  ASN1_Object* ef_upbakpara_317 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_upbakpara", "BF20", true, false, nullptr);
  ASN1_Object* ef_mmsn_318 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsn", "BF21", true, false, nullptr);
  ASN1_Object* ef_ext8_319 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext8", "BF22", true, false, nullptr);
  ASN1_Object* ef_mmsicp_320 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsicp", "BF23", true, false, nullptr);
  ASN1_Object* ef_mmsup_321 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsup", "BF24", true, false, nullptr);
  ASN1_Object* ef_mmsucp_322 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsucp", "BF25", true, false, nullptr);
  ASN1_Object* ef_auth_capability_323 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_auth_capability", "BF26", true, false, nullptr);
  ASN1_Object* ef_3gcik_324 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_3gcik", "BF27", true, false, nullptr);
  ASN1_Object* ef_dck_325 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_dck", "BF28", true, false, nullptr);
  ASN1_Object* ef_gid1_326 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gid1", "BF29", true, false, nullptr);
  ASN1_Object* ef_gid2_327 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_gid2", "BF2A", true, false, nullptr);
  ASN1_Object* ef_cdmacnl_328 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_cdmacnl", "BF2B", true, false, nullptr);
  ASN1_Object* ef_sf_eumid_329 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sf_eumid", "BF2C", true, false, nullptr);
  ASN1_Object* ef_est_330 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_est", "BF2D", true, false, nullptr);
  ASN1_Object* ef_hidden_key_331 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_hidden_key", "BF2E", true, false, nullptr);
  ASN1_Object* ef_lcsver_332 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_lcsver", "BF2F", true, false, nullptr);
  ASN1_Object* ef_lcscp_333 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_lcscp", "BF30", true, false, nullptr);
  ASN1_Object* ef_sdn_334 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_sdn", "BF31", true, false, nullptr);
  ASN1_Object* ef_ext2_335 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext2", "BF32", true, false, nullptr);
  ASN1_Object* ef_ext3_336 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext3", "BF33", true, false, nullptr);
  ASN1_Object* ef_ici_337 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ici", "BF34", true, false, nullptr);
  ASN1_Object* ef_oci_338 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_oci", "BF35", true, false, nullptr);
  ASN1_Object* ef_ext5_339 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ext5", "BF36", true, false, nullptr);
  ASN1_Object* ef_ccp2_340 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ccp2", "BF37", true, false, nullptr);
  ASN1_Object* ef_applabels_341 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_applabels", "BF38", true, false, nullptr);
  ASN1_Object* ef_model_342 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_model", "BF39", true, false, nullptr);
  ASN1_Object* ef_rc_343 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_rc", "BF3A", true, false, nullptr);
  ASN1_Object* ef_smscap_344 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_smscap", "BF3B", true, false, nullptr);
  ASN1_Object* ef_mipflags_345 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mipflags", "BF3C", true, false, nullptr);
  ASN1_Object* ef_3gpduppext_346 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_3gpduppext", "BF3D", true, false, nullptr);
  ASN1_Object* ef_ipv6cap_347 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_ipv6cap", "BF3E", true, false, nullptr);
  ASN1_Object* ef_tcpconfig_348 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_tcpconfig", "BF3F", true, false, nullptr);
  ASN1_Object* ef_dgc_349 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_dgc", "BF40", true, false, nullptr);
  ASN1_Object* ef_wapbrowsercp_350 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_wapbrowsercp", "BF41", true, false, nullptr);
  ASN1_Object* ef_wapbrowserbm_351 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_wapbrowserbm", "BF42", true, false, nullptr);
  ASN1_Object* ef_mmsconfig_352 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_mmsconfig", "BF43", true, false, nullptr);
  ASN1_Object* ef_jdl_353 = new ASN1_SequenceOf({&File_SeqOfCallback, nullptr}, "ef_jdl", "BF44", true, false, nullptr);
  arr[0] = optcsim_header_285; arr[1] = templateID_286; arr[2] = ef_ssci_287; arr[3] = ef_fdn_288; arr[4] = ef_sms_289; arr[5] = ef_smsp_290; arr[6] = ef_smss_291; arr[7] = ef_ssfc_292;
  arr[8] = ef_spn_293; arr[9] = ef_mdn_294; arr[10] = ef_ecc_295; arr[11] = ef_me3gpdopc_296; arr[12] = ef_3gpdopm_297; arr[13] = ef_sipcap_298; arr[14] = ef_mipcap_299; arr[15] = ef_sipupp_300;
  arr[16] = ef_mipupp_301; arr[17] = ef_sipsp_302; arr[18] = ef_mipsp_303; arr[19] = ef_sippapss_304; arr[20] = ef_puzl_305; arr[21] = ef_maxpuzl_306; arr[22] = ef_hrpdcap_307; arr[23] = ef_hrpdupp_308;
  arr[24] = ef_csspr_309; arr[25] = ef_atc_310; arr[26] = ef_eprl_311; arr[27] = ef_bcsmscfg_312; arr[28] = ef_bcsmspref_313; arr[29] = ef_bcsmstable_314; arr[30] = ef_bcsmsp_315;
  arr[31] = ef_bakpara_316; arr[32] = ef_upbakpara_317; arr[33] = ef_mmsn_318; arr[34] = ef_ext8_319; arr[35] = ef_mmsicp_320; arr[36] = ef_mmsup_321; arr[37] = ef_mmsucp_322;
  arr[38] = ef_auth_capability_323; arr[39] = ef_3gcik_324; arr[40] = ef_dck_325; arr[41] = ef_gid1_326; arr[42] = ef_gid2_327; arr[43] = ef_cdmacnl_328; arr[44] = ef_sf_eumid_329; arr[45] = ef_est_330;
  arr[46] = ef_hidden_key_331; arr[47] = ef_lcsver_332; arr[48] = ef_lcscp_333; arr[49] = ef_sdn_334; arr[50] = ef_ext2_335; arr[51] = ef_ext3_336; arr[52] = ef_ici_337; arr[53] = ef_oci_338;
  arr[54] = ef_ext5_339; arr[55] = ef_ccp2_340; arr[56] = ef_applabels_341; arr[57] = ef_model_342; arr[58] = ef_rc_343; arr[59] = ef_smscap_344; arr[60] = ef_mipflags_345; arr[61] = ef_3gpduppext_346;
  arr[62] = ef_ipv6cap_347; arr[63] = ef_tcpconfig_348; arr[64] = ef_dgc_349; arr[65] = ef_wapbrowsercp_350; arr[66] = ef_wapbrowserbm_351; arr[67] = ef_mmsconfig_352; arr[68] = ef_jdl_353;
}

ASN1_Object* Choice4_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* filePath_354 = new ASN1_OctetString("filePath", "80", false, false, nullptr);
    return filePath_354;
  }
  if (index == 1) {
    ASN1_Object* arr_createFCP_355[10];
    Make_Fcp(arr_createFCP_355);
    ASN1_Object* createFCP_355 = new ASN1_Sequence(arr_createFCP_355, 10, "createFCP", "62", false, false, nullptr, true);
    return createFCP_355;
  }
  if (index == 2) {
    ASN1_Object* fillFileOffset_356 = Make_UInt16("fillFileOffset", "", false, false, nullptr);
    return fillFileOffset_356;
  }
  if (index == 3) {
    ASN1_Object* fillFileContent_357 = new ASN1_OctetString("fillFileContent", "81", false, false, nullptr);
    return fillFileContent_357;
  }
  return nullptr;
}

ASN1_Object* FileManagement_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_358 = new ASN1_Choice({&Choice4_ChoiceCallback, nullptr}, 4, "SeqOfVar", "A0", false, true, nullptr);
  return SeqOfVar_358;
}

void Make_MappingParameter(ASN1_Object** arr) {
  ASN1_Object* mappingOptions_359 = new ASN1_OctetString("mappingOptions", "80", false, false, nullptr);
  ASN1_Object* mappingSource_360 = Make_ApplicationIdentifier("mappingSource", "81", false, false, nullptr);
  arr[0] = mappingOptions_359; arr[1] = mappingSource_360;
}

ASN1_Object* SequenceOf5_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_361 = new ASN1_OctetString("SeqOfVar", "80", false, false, nullptr);
  return SeqOfVar_361;
}

void Make_AlgoParameter(ASN1_Object** arr) {
  ASN1_Object* key_362 = new ASN1_OctetString("key", "80", false, false, nullptr);
  ASN1_Object* opc_363 = new ASN1_OctetString("opc", "81", false, false, nullptr);
  ASN1_Object* rotationConstants_364 = new ASN1_OctetString("rotationConstants", "82", false, false, nullptr);
  ASN1_Object* xoringConstants_365 = new ASN1_OctetString("xoringConstants", "83", false, false, nullptr);
  ASN1_Object* sqnInit_366 = new ASN1_SequenceOf({&SequenceOf5_SeqOfCallback, nullptr}, "sqnInit", "A4", false, false, nullptr);
  arr[0] = key_362; arr[1] = opc_363; arr[2] = rotationConstants_364; arr[3] = xoringConstants_365; arr[4] = sqnInit_366;
}

ASN1_Object* Choice6_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* arr_mappingParameter_367[2];
    Make_MappingParameter(arr_mappingParameter_367);
    ASN1_Object* mappingParameter_367 = new ASN1_Sequence(arr_mappingParameter_367, 2, "mappingParameter", "A0", false, false, nullptr, true);
    return mappingParameter_367;
  }
  if (index == 1) {
    ASN1_Object* arr_algoParameter_368[5];
    Make_AlgoParameter(arr_algoParameter_368);
    ASN1_Object* algoParameter_368 = new ASN1_Sequence(arr_algoParameter_368, 5, "algoParameter", "A1", false, false, nullptr, true);
    return algoParameter_368;
  }
  return nullptr;
}

void Make_PE_AKAParameter(ASN1_Object** arr) {
  ASN1_Object* arr_aka_header_369[2];
  Make_PEHeader(arr_aka_header_369);
  ASN1_Object* aka_header_369 = new ASN1_Sequence(arr_aka_header_369, 2, "aka_header", "A0", false, false, nullptr, true);
  ASN1_Object* algorithmID_370 = new ASN1_Integer("algorithmID", "81", false, false, nullptr);
  ASN1_Object* algorithmOptions_371 = new ASN1_OctetString("algorithmOptions", "82", false, false, nullptr);
  ASN1_Object* algoConfiguration_372 = new ASN1_Choice({&Choice6_ChoiceCallback, nullptr}, 2, "algoConfiguration", "A3", false, true, nullptr);
  ASN1_Object* sqnOptions_373 = new ASN1_OctetString("sqnOptions", "84", false, false, nullptr);
  ASN1_Object* sqnDelta_374 = new ASN1_OctetString("sqnDelta", "85", false, false, nullptr);
  ASN1_Object* sqnAgeLimit_375 = new ASN1_OctetString("sqnAgeLimit", "86", false, false, nullptr);
  ASN1_Object* authCounterMax_376 = new ASN1_OctetString("authCounterMax", "87", true, false, nullptr);
  arr[0] = aka_header_369; arr[1] = algorithmID_370; arr[2] = algorithmOptions_371; arr[3] = algoConfiguration_372; arr[4] = sqnOptions_373; arr[5] = sqnDelta_374; arr[6] = sqnAgeLimit_375;
  arr[7] = authCounterMax_376;
}

void Make_PE_CDMAParameter(ASN1_Object** arr) {
  ASN1_Object* arr_cdma_header_377[2];
  Make_PEHeader(arr_cdma_header_377);
  ASN1_Object* cdma_header_377 = new ASN1_Sequence(arr_cdma_header_377, 2, "cdma_header", "A0", false, false, nullptr, true);
  ASN1_Object* authenticationKey_378 = new ASN1_OctetString("authenticationKey", "81", false, false, nullptr);
  ASN1_Object* ssd_379 = new ASN1_OctetString("ssd", "82", true, false, nullptr);
  ASN1_Object* hrpdAccessAuthenticationData_380 = new ASN1_OctetString("hrpdAccessAuthenticationData", "83", true, false, nullptr);
  ASN1_Object* simpleIPAuthenticationData_381 = new ASN1_OctetString("simpleIPAuthenticationData", "84", true, false, nullptr);
  ASN1_Object* mobileIPAuthenticationData_382 = new ASN1_OctetString("mobileIPAuthenticationData", "85", true, false, nullptr);
  arr[0] = cdma_header_377; arr[1] = authenticationKey_378; arr[2] = ssd_379; arr[3] = hrpdAccessAuthenticationData_380; arr[4] = simpleIPAuthenticationData_381; arr[5] = mobileIPAuthenticationData_382;
}

ASN1_Object* Make_PINKeyReferenceValue(const char* name, const char* tag, bool optional, bool explTag, ASN1_Integer* defaultVal) {
  ASN1_Object* var_383 = new ASN1_Integer(name, tag, optional, explTag, defaultVal);
  return var_383;
}

ASN1_Object* Make_PUKKeyReferenceValue(const char* name, const char* tag, bool optional, bool explTag, ASN1_Integer* defaultVal) {
  ASN1_Object* var_384 = new ASN1_Integer(name, tag, optional, explTag, defaultVal);
  return var_384;
}

void Make_PUKConfiguration(ASN1_Object** arr) {
  ASN1_Object* keyReference_385 = Make_PUKKeyReferenceValue("keyReference", "80", false, false, nullptr);
  ASN1_Object* pukValue_386 = new ASN1_OctetString("pukValue", "81", false, false, nullptr);
  ASN1_Object* maxNumOfAttemps_retryNumLeft_387 = Make_UInt8("maxNumOfAttemps_retryNumLeft", "82", false, false, nullptr);
  arr[0] = keyReference_385; arr[1] = pukValue_386; arr[2] = maxNumOfAttemps_retryNumLeft_387;
}

ASN1_Object* SequenceOf9_SeqOfCallback(void*) {
  ASN1_Object* arr_SeqOfVar_388[3];
  Make_PUKConfiguration(arr_SeqOfVar_388);
  ASN1_Object* SeqOfVar_388 = new ASN1_Sequence(arr_SeqOfVar_388, 3, "SeqOfVar", "A0", false, false, nullptr, true);
  return SeqOfVar_388;
}

void Make_PE_PUKCodes(ASN1_Object** arr) {
  ASN1_Object* arr_puk_Header_389[2];
  Make_PEHeader(arr_puk_Header_389);
  ASN1_Object* puk_Header_389 = new ASN1_Sequence(arr_puk_Header_389, 2, "puk_Header", "A0", false, false, nullptr, true);
  ASN1_Object* pukCodes_390 = new ASN1_SequenceOf({&SequenceOf9_SeqOfCallback, nullptr}, "pukCodes", "A1", false, false, nullptr);
  arr[0] = puk_Header_389; arr[1] = pukCodes_390;
}

ASN1_Object* SequenceOf11_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_391 = new ASN1_OctetString("SeqOfVar", "80", false, false, nullptr);
  return SeqOfVar_391;
}

void Make_Sequence12(ASN1_Object** arr) {
  ASN1_Object* keyType_392 = new ASN1_OctetString("keyType", "80", false, false, nullptr);
  ASN1_Object* keyData_393 = new ASN1_OctetString("keyData", "86", false, false, nullptr);
  arr[0] = keyType_392; arr[1] = keyData_393;
}

ASN1_Object* SequenceOf13_SeqOfCallback(void*) {
  ASN1_Object* arr_SeqOfVar_394[2];
  Make_Sequence12(arr_SeqOfVar_394);
  ASN1_Object* SeqOfVar_394 = new ASN1_Sequence(arr_SeqOfVar_394, 2, "SeqOfVar", "A0", false, false, nullptr, true);
  return SeqOfVar_394;
}

void Make_KeyObject(ASN1_Object** arr) {
  ASN1_Object* keyUsageQualifier_395 = new ASN1_OctetString("keyUsageQualifier", "95", false, false, nullptr);
  ASN1_Object* keyAccess_396 = new ASN1_OctetString("keyAccess", "96", false, false, nullptr);
  ASN1_Object* keyIdentifier_397 = new ASN1_OctetString("keyIdentifier", "82", false, false, nullptr);
  ASN1_Object* keyVersionNumber_398 = new ASN1_OctetString("keyVersionNumber", "83", false, false, nullptr);
  ASN1_Object* keyCheckValue_399 = new ASN1_OctetString("keyCheckValue", "84", true, false, nullptr);
  ASN1_Object* keyCounterValue_400 = new ASN1_OctetString("keyCounterValue", "85", true, false, nullptr);
  ASN1_Object* scp80SeqCounter_401 = new ASN1_OctetString("scp80SeqCounter", "", true, false, nullptr);
  ASN1_Object* keyCompontents_402 = new ASN1_SequenceOf({&SequenceOf13_SeqOfCallback, nullptr}, "keyCompontents", "", false, false, nullptr);
  arr[0] = keyUsageQualifier_395; arr[1] = keyAccess_396; arr[2] = keyIdentifier_397; arr[3] = keyVersionNumber_398; arr[4] = keyCheckValue_399; arr[5] = keyCounterValue_400;
  arr[6] = scp80SeqCounter_401; arr[7] = keyCompontents_402;
}

void Make_ApplicationLoadPackage(ASN1_Object** arr) {
  ASN1_Object* loadPackageAID_403 = Make_ApplicationIdentifier("loadPackageAID", "4F", false, false, nullptr);
  ASN1_Object* securityDomainAID_404 = Make_ApplicationIdentifier("securityDomainAID", "4F", true, false, nullptr);
  ASN1_Object* nonVolatileCodeLimitC6_405 = new ASN1_OctetString("nonVolatileCodeLimitC6", "C6", true, false, nullptr);
  ASN1_Object* volatileDataLimitC7_406 = new ASN1_OctetString("volatileDataLimitC7", "C7", true, false, nullptr);
  ASN1_Object* nonVolatileDataLimitC8_407 = new ASN1_OctetString("nonVolatileDataLimitC8", "C8", true, false, nullptr);
  ASN1_Object* hashValue_408 = new ASN1_OctetString("hashValue", "C1", true, false, nullptr);
  ASN1_Object* loadBlockObject_409 = new ASN1_OctetString("loadBlockObject", "C4", false, false, nullptr);
  arr[0] = loadPackageAID_403; arr[1] = securityDomainAID_404; arr[2] = nonVolatileCodeLimitC6_405; arr[3] = volatileDataLimitC7_406; arr[4] = nonVolatileDataLimitC8_407; arr[5] = hashValue_408;
  arr[6] = loadBlockObject_409;
}

ASN1_Object* SequenceOf15_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_410 = new ASN1_OctetString("SeqOfVar", "80", false, false, nullptr);
  return SeqOfVar_410;
}

void Make_UICCApplicationParameters(ASN1_Object** arr) {
  ASN1_Object* uiccToolkitApplicationSpecificParametersField_411 = new ASN1_OctetString("uiccToolkitApplicationSpecificParametersField", "80", true, false, nullptr);
  ASN1_Object* uiccAccessApplicationSpecificParametersField_412 = new ASN1_OctetString("uiccAccessApplicationSpecificParametersField", "83", true, false, nullptr);
  ASN1_Object* uiccAccessParams_413 = new ASN1_OctetString("uiccAccessParams", "81", true, false, nullptr);
  ASN1_Object* uiccAdministrativeAccessApplicationSpecificParametersField_414 = new ASN1_OctetString("uiccAdministrativeAccessApplicationSpecificParametersField", "82", true, false, nullptr);
  arr[0] = uiccToolkitApplicationSpecificParametersField_411; arr[1] = uiccAccessApplicationSpecificParametersField_412; arr[2] = uiccAccessParams_413;
  arr[3] = uiccAdministrativeAccessApplicationSpecificParametersField_414;
}

void Make_TS102226AdditionalContactlessParameters(ASN1_Object** arr) {
  ASN1_Object* protocolParameterData_415 = new ASN1_OctetString("protocolParameterData", "80", false, false, nullptr);
  arr[0] = protocolParameterData_415;
}

ASN1_Object* SequenceOf16_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_416 = new ASN1_OctetString("SeqOfVar", "80", false, false, nullptr);
  return SeqOfVar_416;
}

void Make_ADFRFMAccess(ASN1_Object** arr) {
  ASN1_Object* adfAID_417 = Make_ApplicationIdentifier("adfAID", "80", false, false, nullptr);
  ASN1_Object* adfAccessDomain_418 = new ASN1_OctetString("adfAccessDomain", "81", false, false, nullptr);
  ASN1_Object* adfAdminAccessDomain_419 = new ASN1_OctetString("adfAdminAccessDomain", "82", false, false, nullptr);
  arr[0] = adfAID_417; arr[1] = adfAccessDomain_418; arr[2] = adfAdminAccessDomain_419;
}

void Make_PE_NonStandard(ASN1_Object** arr) {
  ASN1_Object* arr_nonStandard_header_420[2];
  Make_PEHeader(arr_nonStandard_header_420);
  ASN1_Object* nonStandard_header_420 = new ASN1_Sequence(arr_nonStandard_header_420, 2, "nonStandard_header", "A0", false, false, nullptr, true);
  ASN1_Object* issuerID_421 = new ASN1_ObjectID("issuerID", "81", false, false, nullptr);
  ASN1_Object* content_422 = new ASN1_OctetString("content", "82", false, false, nullptr);
  arr[0] = nonStandard_header_420; arr[1] = issuerID_421; arr[2] = content_422;
}

void Make_PE_End(ASN1_Object** arr) {
  ASN1_Object* arr_end_header_423[2];
  Make_PEHeader(arr_end_header_423);
  ASN1_Object* end_header_423 = new ASN1_Sequence(arr_end_header_423, 2, "end_header", "A0", false, false, nullptr, true);
  arr[0] = end_header_423;
}

ASN1_Object* SequenceOf3_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_424 = new ASN1_SequenceOf({&FileManagement_SeqOfCallback, nullptr}, "SeqOfVar", "A0", false, false, nullptr);
  return SeqOfVar_424;
}

void Make_PE_GenericFileManagement(ASN1_Object** arr) {
  ASN1_Object* arr_gfm_header_425[2];
  Make_PEHeader(arr_gfm_header_425);
  ASN1_Object* gfm_header_425 = new ASN1_Sequence(arr_gfm_header_425, 2, "gfm_header", "A0", false, false, nullptr, true);
  ASN1_Object* fileManagementCMD_426 = new ASN1_SequenceOf({&SequenceOf3_SeqOfCallback, nullptr}, "fileManagementCMD", "A1", false, false, nullptr);
  arr[0] = gfm_header_425; arr[1] = fileManagementCMD_426;
}

void Make_PINConfiguration(ASN1_Object** arr) {
  ASN1_Object* keyReference_427 = Make_PINKeyReferenceValue("keyReference", "80", false, false, nullptr);
  ASN1_Object* pinValue_428 = new ASN1_OctetString("pinValue", "81", false, false, nullptr);
  ASN1_Object* unblockingPINReference_429 = Make_PUKKeyReferenceValue("unblockingPINReference", "82", true, false, nullptr);
  ASN1_Object* pinAttributes_430 = Make_UInt8("pinAttributes", "83", false, false, nullptr);
  ASN1_Object* maxNumOfAttemps_retryNumLeft_431 = Make_UInt8("maxNumOfAttemps_retryNumLeft", "84", false, false, nullptr);
  arr[0] = keyReference_427; arr[1] = pinValue_428; arr[2] = unblockingPINReference_429; arr[3] = pinAttributes_430; arr[4] = maxNumOfAttemps_retryNumLeft_431;
}

ASN1_Object* SequenceOf7_SeqOfCallback(void*) {
  ASN1_Object* arr_SeqOfVar_432[5];
  Make_PINConfiguration(arr_SeqOfVar_432);
  ASN1_Object* SeqOfVar_432 = new ASN1_Sequence(arr_SeqOfVar_432, 5, "SeqOfVar", "A0", false, false, nullptr, true);
  return SeqOfVar_432;
}

ASN1_Object* Choice8_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* pinconfig_433 = new ASN1_SequenceOf({&SequenceOf7_SeqOfCallback, nullptr}, "pinconfig", "A0", false, false, nullptr);
    return pinconfig_433;
  }
  if (index == 1) {
    ASN1_Object* filePath_434 = new ASN1_OctetString("filePath", "81", false, false, nullptr);
    return filePath_434;
  }
  return nullptr;
}

void Make_PE_PINCodes(ASN1_Object** arr) {
  ASN1_Object* arr_pin_Header_435[2];
  Make_PEHeader(arr_pin_Header_435);
  ASN1_Object* pin_Header_435 = new ASN1_Sequence(arr_pin_Header_435, 2, "pin_Header", "A0", false, false, nullptr, true);
  ASN1_Object* pinCodes_436 = new ASN1_Choice({&Choice8_ChoiceCallback, nullptr}, 2, "pinCodes", "A1", false, true, nullptr);
  arr[0] = pin_Header_435; arr[1] = pinCodes_436;
}

ASN1_Object* SequenceOf10_SeqOfCallback(void*) {
  ASN1_Object* arr_SeqOfVar_437[8];
  Make_KeyObject(arr_SeqOfVar_437);
  ASN1_Object* SeqOfVar_437 = new ASN1_Sequence(arr_SeqOfVar_437, 8, "SeqOfVar", "A0", false, false, nullptr, true);
  return SeqOfVar_437;
}

void Make_ApplicationSystemParameters(ASN1_Object** arr) {
  ASN1_Object* volatileMemoryQuotaC7_438 = new ASN1_OctetString("volatileMemoryQuotaC7", "C7", true, false, nullptr);
  ASN1_Object* nonVolatileMemoryQuotaC8_439 = new ASN1_OctetString("nonVolatileMemoryQuotaC8", "C8", true, false, nullptr);
  ASN1_Object* globalServiceParameters_440 = new ASN1_OctetString("globalServiceParameters", "CB", true, false, nullptr);
  ASN1_Object* implicitSelectionParameter_441 = new ASN1_OctetString("implicitSelectionParameter", "CF", true, false, nullptr);
  ASN1_Object* volatileReservedMemory_442 = new ASN1_OctetString("volatileReservedMemory", "D7", true, false, nullptr);
  ASN1_Object* nonVolatileReservedMemory_443 = new ASN1_OctetString("nonVolatileReservedMemory", "D8", true, false, nullptr);
  ASN1_Object* ts102226SIMFileAccessToolkitParameter_444 = new ASN1_OctetString("ts102226SIMFileAccessToolkitParameter", "CA", true, false, nullptr);
  ASN1_Object* arr_ts102226AdditionalContactlessParameters_445[1];
  Make_TS102226AdditionalContactlessParameters(arr_ts102226AdditionalContactlessParameters_445);
  ASN1_Object* ts102226AdditionalContactlessParameters_445 = new ASN1_Sequence(arr_ts102226AdditionalContactlessParameters_445, 1, "ts102226AdditionalContactlessParameters", "A0", true, false, nullptr,
      true);
  arr[0] = volatileMemoryQuotaC7_438; arr[1] = nonVolatileMemoryQuotaC8_439; arr[2] = globalServiceParameters_440; arr[3] = implicitSelectionParameter_441; arr[4] = volatileReservedMemory_442;
  arr[5] = nonVolatileReservedMemory_443; arr[6] = ts102226SIMFileAccessToolkitParameter_444; arr[7] = ts102226AdditionalContactlessParameters_445;
}

void Make_PE_RFM(ASN1_Object** arr) {
  ASN1_Object* arr_rfm_header_446[2];
  Make_PEHeader(arr_rfm_header_446);
  ASN1_Object* rfm_header_446 = new ASN1_Sequence(arr_rfm_header_446, 2, "rfm_header", "", false, false, nullptr, true);
  ASN1_Object* securityDomainAID_447 = Make_ApplicationIdentifier("securityDomainAID", "4F", false, false, nullptr);
  ASN1_Object* tarList_448 = new ASN1_SequenceOf({&SequenceOf16_SeqOfCallback, nullptr}, "tarList", "A0", false, false, nullptr);
  ASN1_Object* minimumSecurityLevel_449 = new ASN1_OctetString("minimumSecurityLevel", "81", false, false, nullptr);
  ASN1_Object* uiccAccessDomain_450 = new ASN1_OctetString("uiccAccessDomain", "", false, false, nullptr);
  ASN1_Object* uiccAdminAccessDomain_451 = new ASN1_OctetString("uiccAdminAccessDomain", "", false, false, nullptr);
  ASN1_Object* arr_adfRFMAccess_452[3];
  Make_ADFRFMAccess(arr_adfRFMAccess_452);
  ASN1_Object* adfRFMAccess_452 = new ASN1_Sequence(arr_adfRFMAccess_452, 3, "adfRFMAccess", "", true, false, nullptr, true);
  arr[0] = rfm_header_446; arr[1] = securityDomainAID_447; arr[2] = tarList_448; arr[3] = minimumSecurityLevel_449; arr[4] = uiccAccessDomain_450; arr[5] = uiccAdminAccessDomain_451;
  arr[6] = adfRFMAccess_452;
}

void Make_ApplicationInstance(ASN1_Object** arr) {
  ASN1_Object* applicationLoadPackageAID_453 = Make_ApplicationIdentifier("applicationLoadPackageAID", "4F", false, false, nullptr);
  ASN1_Object* classAID_454 = Make_ApplicationIdentifier("classAID", "4F", false, false, nullptr);
  ASN1_Object* instanceAID_455 = Make_ApplicationIdentifier("instanceAID", "4F", false, false, nullptr);
  ASN1_Object* extraditeSecurityDomainAID_456 = Make_ApplicationIdentifier("extraditeSecurityDomainAID", "4F", true, false, nullptr);
  ASN1_Object* applicationPrivileges_457 = new ASN1_OctetString("applicationPrivileges", "82", false, false, nullptr);
  ASN1_Object* lifeCycleState_458 = new ASN1_OctetString("lifeCycleState", "83", false, false, nullptr);
  ASN1_Object* applicationSpecificParametersC9_459 = new ASN1_OctetString("applicationSpecificParametersC9", "C9", false, false, nullptr);
  ASN1_Object* arr_systemSpecificParameters_460[8];
  Make_ApplicationSystemParameters(arr_systemSpecificParameters_460);
  ASN1_Object* systemSpecificParameters_460 = new ASN1_Sequence(arr_systemSpecificParameters_460, 8, "systemSpecificParameters", "EF", true, false, nullptr, true);
  ASN1_Object* arr_applicationParameters_461[4];
  Make_UICCApplicationParameters(arr_applicationParameters_461);
  ASN1_Object* applicationParameters_461 = new ASN1_Sequence(arr_applicationParameters_461, 4, "applicationParameters", "EA", true, false, nullptr, true);
  ASN1_Object* processData_462 = new ASN1_SequenceOf({&SequenceOf15_SeqOfCallback, nullptr}, "processData", "", true, false, nullptr);
  arr[0] = applicationLoadPackageAID_453; arr[1] = classAID_454; arr[2] = instanceAID_455; arr[3] = extraditeSecurityDomainAID_456; arr[4] = applicationPrivileges_457; arr[5] = lifeCycleState_458;
  arr[6] = applicationSpecificParametersC9_459; arr[7] = systemSpecificParameters_460; arr[8] = applicationParameters_461; arr[9] = processData_462;
}

void Make_PE_SecurityDomain(ASN1_Object** arr) {
  ASN1_Object* arr_sd_Header_463[2];
  Make_PEHeader(arr_sd_Header_463);
  ASN1_Object* sd_Header_463 = new ASN1_Sequence(arr_sd_Header_463, 2, "sd_Header", "A0", false, false, nullptr, true);
  ASN1_Object* arr_instance_464[10];
  Make_ApplicationInstance(arr_instance_464);
  ASN1_Object* instance_464 = new ASN1_Sequence(arr_instance_464, 10, "instance", "A1", false, false, nullptr, true);
  ASN1_Object* keyList_465 = new ASN1_SequenceOf({&SequenceOf10_SeqOfCallback, nullptr}, "keyList", "A2", true, false, nullptr);
  ASN1_Object* sdPersoData_466 = new ASN1_SequenceOf({&SequenceOf11_SeqOfCallback, nullptr}, "sdPersoData", "A3", true, false, nullptr);
  arr[0] = sd_Header_463; arr[1] = instance_464; arr[2] = keyList_465; arr[3] = sdPersoData_466;
}

ASN1_Object* SequenceOf14_SeqOfCallback(void*) {
  ASN1_Object* arr_SeqOfVar_467[10];
  Make_ApplicationInstance(arr_SeqOfVar_467);
  ASN1_Object* SeqOfVar_467 = new ASN1_Sequence(arr_SeqOfVar_467, 10, "SeqOfVar", "A0", false, false, nullptr, true);
  return SeqOfVar_467;
}

void Make_PE_Application(ASN1_Object** arr) {
  ASN1_Object* arr_app_Header_468[2];
  Make_PEHeader(arr_app_Header_468);
  ASN1_Object* app_Header_468 = new ASN1_Sequence(arr_app_Header_468, 2, "app_Header", "A0", false, false, nullptr, true);
  ASN1_Object* arr_loadBlock_469[7];
  Make_ApplicationLoadPackage(arr_loadBlock_469);
  ASN1_Object* loadBlock_469 = new ASN1_Sequence(arr_loadBlock_469, 7, "loadBlock", "A1", true, false, nullptr, true);
  ASN1_Object* instanceList_470 = new ASN1_SequenceOf({&SequenceOf14_SeqOfCallback, nullptr}, "instanceList", "A2", true, false, nullptr);
  arr[0] = app_Header_468; arr[1] = loadBlock_469; arr[2] = instanceList_470;
}

ASN1_Object* ProfileElement_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* arr_header_471[7];
    Make_ProfileHeader(arr_header_471);
    ASN1_Object* header_471 = new ASN1_Sequence(arr_header_471, 7, "header", "A0", false, false, nullptr, true);
    return header_471;
  }
  if (index == 1) {
    ASN1_Object* arr_genericFileManagement_472[2];
    Make_PE_GenericFileManagement(arr_genericFileManagement_472);
    ASN1_Object* genericFileManagement_472 = new ASN1_Sequence(arr_genericFileManagement_472, 2, "genericFileManagement", "A1", false, false, nullptr, true);
    return genericFileManagement_472;
  }
  if (index == 2) {
    ASN1_Object* arr_pinCodes_473[2];
    Make_PE_PINCodes(arr_pinCodes_473);
    ASN1_Object* pinCodes_473 = new ASN1_Sequence(arr_pinCodes_473, 2, "pinCodes", "A2", false, false, nullptr, true);
    return pinCodes_473;
  }
  if (index == 3) {
    ASN1_Object* arr_pukCodes_474[2];
    Make_PE_PUKCodes(arr_pukCodes_474);
    ASN1_Object* pukCodes_474 = new ASN1_Sequence(arr_pukCodes_474, 2, "pukCodes", "A3", false, false, nullptr, true);
    return pukCodes_474;
  }
  if (index == 4) {
    ASN1_Object* arr_akaParameter_475[8];
    Make_PE_AKAParameter(arr_akaParameter_475);
    ASN1_Object* akaParameter_475 = new ASN1_Sequence(arr_akaParameter_475, 8, "akaParameter", "A4", false, false, nullptr, true);
    return akaParameter_475;
  }
  if (index == 5) {
    ASN1_Object* arr_cdmaParameter_476[6];
    Make_PE_CDMAParameter(arr_cdmaParameter_476);
    ASN1_Object* cdmaParameter_476 = new ASN1_Sequence(arr_cdmaParameter_476, 6, "cdmaParameter", "A5", false, false, nullptr, true);
    return cdmaParameter_476;
  }
  if (index == 6) {
    ASN1_Object* arr_securityDomain_477[4];
    Make_PE_SecurityDomain(arr_securityDomain_477);
    ASN1_Object* securityDomain_477 = new ASN1_Sequence(arr_securityDomain_477, 4, "securityDomain", "A6", false, false, nullptr, true);
    return securityDomain_477;
  }
  if (index == 7) {
    ASN1_Object* arr_rfm_478[7];
    Make_PE_RFM(arr_rfm_478);
    ASN1_Object* rfm_478 = new ASN1_Sequence(arr_rfm_478, 7, "rfm", "A7", false, false, nullptr, true);
    return rfm_478;
  }
  if (index == 8) {
    ASN1_Object* arr_application_479[3];
    Make_PE_Application(arr_application_479);
    ASN1_Object* application_479 = new ASN1_Sequence(arr_application_479, 3, "application", "A8", false, false, nullptr, true);
    return application_479;
  }
  if (index == 9) {
    ASN1_Object* arr_nonStandard_480[3];
    Make_PE_NonStandard(arr_nonStandard_480);
    ASN1_Object* nonStandard_480 = new ASN1_Sequence(arr_nonStandard_480, 3, "nonStandard", "A9", false, false, nullptr, true);
    return nonStandard_480;
  }
  if (index == 10) {
    ASN1_Object* arr_end_481[1];
    Make_PE_End(arr_end_481);
    ASN1_Object* end_481 = new ASN1_Sequence(arr_end_481, 1, "end", "AA", false, false, nullptr, true);
    return end_481;
  }
  if (index == 11) {
    ASN1_Object** arr_rfu1_482 = nullptr;
    Make_PE_Dummy(arr_rfu1_482);
    ASN1_Object* rfu1_482 = new ASN1_Sequence(arr_rfu1_482, 0, "rfu1", "AB", false, false, nullptr, true);
    return rfu1_482;
  }
  if (index == 12) {
    ASN1_Object** arr_rfu2_483 = nullptr;
    Make_PE_Dummy(arr_rfu2_483);
    ASN1_Object* rfu2_483 = new ASN1_Sequence(arr_rfu2_483, 0, "rfu2", "AC", false, false, nullptr, true);
    return rfu2_483;
  }
  if (index == 13) {
    ASN1_Object** arr_rfu3_484 = nullptr;
    Make_PE_Dummy(arr_rfu3_484);
    ASN1_Object* rfu3_484 = new ASN1_Sequence(arr_rfu3_484, 0, "rfu3", "AD", false, false, nullptr, true);
    return rfu3_484;
  }
  if (index == 14) {
    ASN1_Object** arr_rfu4_485 = nullptr;
    Make_PE_Dummy(arr_rfu4_485);
    ASN1_Object* rfu4_485 = new ASN1_Sequence(arr_rfu4_485, 0, "rfu4", "AE", false, false, nullptr, true);
    return rfu4_485;
  }
  if (index == 15) {
    ASN1_Object** arr_rfu5_486 = nullptr;
    Make_PE_Dummy(arr_rfu5_486);
    ASN1_Object* rfu5_486 = new ASN1_Sequence(arr_rfu5_486, 0, "rfu5", "AF", false, false, nullptr, true);
    return rfu5_486;
  }
  if (index == 16) {
    ASN1_Object* arr_mf_487[7];
    Make_PE_MF(arr_mf_487);
    ASN1_Object* mf_487 = new ASN1_Sequence(arr_mf_487, 7, "mf", "B0", false, false, nullptr, true);
    return mf_487;
  }
  if (index == 17) {
    ASN1_Object* arr_cd_488[5];
    Make_PE_CD(arr_cd_488);
    ASN1_Object* cd_488 = new ASN1_Sequence(arr_cd_488, 5, "cd", "B1", false, false, nullptr, true);
    return cd_488;
  }
  if (index == 18) {
    ASN1_Object* arr_telecom_489[40];
    Make_PE_TELECOM(arr_telecom_489);
    ASN1_Object* telecom_489 = new ASN1_Sequence(arr_telecom_489, 40, "telecom", "B2", false, false, nullptr, true);
    return telecom_489;
  }
  if (index == 19) {
    ASN1_Object* arr_usim_490[26];
    Make_PE_USIM(arr_usim_490);
    ASN1_Object* usim_490 = new ASN1_Sequence(arr_usim_490, 26, "usim", "B3", false, false, nullptr, true);
    return usim_490;
  }
  if (index == 20) {
    ASN1_Object* arr_opt_usim_491[75];
    Make_PE_OPT_USIM(arr_opt_usim_491);
    ASN1_Object* opt_usim_491 = new ASN1_Sequence(arr_opt_usim_491, 75, "opt_usim", "B4", false, false, nullptr, true);
    return opt_usim_491;
  }
  if (index == 21) {
    ASN1_Object* arr_isim_492[9];
    Make_PE_ISIM(arr_isim_492);
    ASN1_Object* isim_492 = new ASN1_Sequence(arr_isim_492, 9, "isim", "B5", false, false, nullptr, true);
    return isim_492;
  }
  if (index == 22) {
    ASN1_Object* arr_opt_isim_493[12];
    Make_PE_OPT_ISIM(arr_opt_isim_493);
    ASN1_Object* opt_isim_493 = new ASN1_Sequence(arr_opt_isim_493, 12, "opt_isim", "B6", false, false, nullptr, true);
    return opt_isim_493;
  }
  if (index == 23) {
    ASN1_Object* arr_phonebook_494[20];
    Make_PE_PHONEBOOK(arr_phonebook_494);
    ASN1_Object* phonebook_494 = new ASN1_Sequence(arr_phonebook_494, 20, "phonebook", "B7", false, false, nullptr, true);
    return phonebook_494;
  }
  if (index == 24) {
    ASN1_Object* arr_gsm_access_495[7];
    Make_PE_GSM_ACCESS(arr_gsm_access_495);
    ASN1_Object* gsm_access_495 = new ASN1_Sequence(arr_gsm_access_495, 7, "gsm_access", "B8", false, false, nullptr, true);
    return gsm_access_495;
  }
  if (index == 25) {
    ASN1_Object* arr_csim_496[37];
    Make_PE_CSIM(arr_csim_496);
    ASN1_Object* csim_496 = new ASN1_Sequence(arr_csim_496, 37, "csim", "B9", false, false, nullptr, true);
    return csim_496;
  }
  if (index == 26) {
    ASN1_Object* arr_opt_csim_497[69];
    Make_PE_OPT_CSIM(arr_opt_csim_497);
    ASN1_Object* opt_csim_497 = new ASN1_Sequence(arr_opt_csim_497, 69, "opt_csim", "BA", false, false, nullptr, true);
    return opt_csim_497;
  }
  return nullptr;
}

ASN1_Object* TheProfile_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_498 = new ASN1_Choice({&ProfileElement_ChoiceCallback, nullptr}, 27, "SeqOfVar", "", false, true, nullptr);
  return SeqOfVar_498;
}

ASN1_Object* GetGrammar() {
  ASN1_Object* main_499 = new ASN1_SequenceOf({&TheProfile_SeqOfCallback, nullptr}, "main", "", false, false, nullptr);
  return main_499;
}
