/*  File auto-generated by Q-ASN1. */
#include "ASN1_includes.h"

ASN1_Object* Amod_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* aVar_1 = new ASN1_Integer("aVar", "81", false, false, nullptr);
    return aVar_1;
  }
  if (index == 1) {
    ASN1_Object* bVar_2 = new ASN1_Boolean("bVar", "82", false, false, nullptr);
    return bVar_2;
  }
  return nullptr;
}

ASN1_Object* Bmod_SeqOfCallback(void*) {
  ASN1_Object* SeqOfVar_3 = new ASN1_Choice({&Amod_ChoiceCallback, nullptr}, 2, "SeqOfVar", "A0", false, true, nullptr);
  return SeqOfVar_3;
}

ASN1_Object* Choice1_ChoiceCallback(unsigned int index, void*) {
  if (index == 0) {
    ASN1_Object* cVar_4 = new ASN1_Integer("cVar", "A3", false, true, nullptr);
    return cVar_4;
  }
  if (index == 1) {
    ASN1_Object* dVar_5 = new ASN1_Boolean("dVar", "84", false, false, nullptr);
    return dVar_5;
  }
  return nullptr;
}

void Make_Cmod(ASN1_Object** arr) {
  ASN1_Object* eVar_6 = new ASN1_SequenceOf({&Bmod_SeqOfCallback, nullptr}, "eVar", "A0", false, false, nullptr);
  ASN1_Object* fVar_7 = new ASN1_Choice({&Choice1_ChoiceCallback, nullptr}, 2, "fVar", "A1", false, true, nullptr);
  arr[0] = eVar_6; arr[1] = fVar_7;
}

ASN1_Object* GetGrammar() {
  ASN1_Object* arr_main_8[2];
  Make_Cmod(arr_main_8);
  ASN1_Object* main_8 = new ASN1_Sequence(arr_main_8, 2, "main", "", false, false, nullptr, false);
  return main_8;
}
